name: quality-assurance
on:
  push:
    branches:
     - "*"
     - "*/*"
     - "**"
  pull_request:
    branches:
    - "*"
    - "*/*"
    - "**"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install
      run: yarn install
    - name: Build
      run: |
        echo "${{secrets.ENVFILE}}" > .env.production.local
        yarn run build
        cp dist/index.html dist/404.html
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install
      run: yarn install
    - name: Test
      run: yarn test
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install
      run: yarn install
    - name: Lint
      run: yarn lint